### ISSUE TITLE
Change default folder name - drawable to mipmap

### ISSUE THREAD

**Issue by prakash827** [romannurik/AndroidAssetStudio#102]
Now a days the recommended way is to put the images in mipmap folder. when generating action bar icons, the tool still put the images in drawable-xxx folder. please change it to mipmap. Every times its difficult to change name manually.

**Current structure:**

_drawable-hdpi
drawable-mdpi
drawable-xhdpi
drawable-xxhdpi
drawable-xxxhdpi_

**New recommended structure:**

_mipmap-hdpi
mipmap-mdpi
mipmap-xhdpi
mipmap-xxhdpi
mipmap-xxxhdpi_

**Comment by romannurik** [comment]
Mipmap folders are intended only for launcher icons. Also these days, you should really just be using vector assets :) The asset studio isn't really useful for action bar icons anymore.
