### ISSUE TITLE
Using this for notification icons does not work - they need to be 8bit Grayscale

### ISSUE THREAD

**Issue by pke** [romannurik/AndroidAssetStudio#104]
I tried this tool to check whats wrong with my hand made notification icon. However, the icons generated by this tool also showed up as a white rectangle in notifications (in Android 5.x up).

The key is to change the image format from 32bit+Alpha to 8bit+Alpha **grayscale**.
So it would be better if this tool had an option to save icons as notification icons for Android 5.x in the aformentioned format.

**Comment by romannurik** [comment]
[Working as intended] You actually need to just provide an image with an alpha layer... the alpha layer is all that is used by the tool and by Android.
