### ISSUE TITLE
generic icons generator does not work

### ISSUE THREAD

**Issue by netpork** [romannurik/AndroidAssetStudio#105]
![screenshot from 2016-06-22 13-30-25](https://cloud.githubusercontent.com/assets/680076/16269681/9f0ce7d6-3893-11e6-912f-3501bbbfc27e.png)

I have tried different png files and it is all the same.

**Comment by ChiragSavsani** [comment]
I also have same problem since 2-3 months. 

How to resolve this?

**Comment by jon80** [comment]
I think that the framework has to allow for a usable and easy manipulation of images, one might use existing api's as the basis of re-engineering of the underlying graphics.
Jon

Date: Sun, 26 Jun 2016 23:17:15 -0700

**Comment by virendradj** [comment]
Same thing is happening for Navigation bar icons 
![screencapture-romannurik-github-io-androidassetstudio-icons-notification-html-1469176034859](https://cloud.githubusercontent.com/assets/19606416/17051078/4cac5d3a-5014-11e6-8585-db346670acc7.png)

**Comment by romashko** [comment]
Just change Color from 100% to 0%.

**Comment by romannurik** [comment]
The generators only use the alpha channel in your images, make sure you're importing PNGs with alpha
