### ISSUE TITLE
Android Lint - warning

### ISSUE THREAD

**Issue by Yousha** [romannurik/AndroidAssetStudio#109]
Android Lint gives warning when using icons that generated by your script:

```
Incorrect icon size for drawable-xxhdpi\ic_stat_launcher.png: icon size should be at most 48x48, but was 72x72

Issue: Ensures that launcher icons, notification icons etc have the correct size
Id: IconExpectedSize

There are predefined sizes (for each density) for launcher icons. You should follow these conventions to make sure your icons fit in with the overall look of the platform.

[http://developer.android.com/design/style/iconography.html]
```

**Comment by romannurik** [comment]
Can you attach the icon here?

This might just be a bug in lint, since xxhdpi is 3x and notification icons are 24dp (24dp at 3x is 72px)

**Comment by Yousha** [comment]
I made this for notification/status:

used this one in drawable-hdpi-v11 directory:
http://uupload.ir/files/4igv_ic_stat_ic_launcher_web.png

Eclipse 4.5, Compiler for Android 2 to 4

**Comment by romannurik** [comment]
Ah, this is likely related to API levels. The icon generated there is for API 9-10, and the lint check may be expecting API 11+ notification icons. On top of that, lint seems to have its densities wrong. I'd file a bug on lint in the Android bug tracker :)
