### ISSUE TITLE
TEXT Ican cannot created

### ISSUE THREAD

**Issue by jsroyal** [romannurik/AndroidAssetStudio#112]
I want to create Text Icon Example "TravelDiaries " which has I created icon in circle  type but the whole text does not show.

**Comment by jsroyal** [comment]
![screenshot from 2016-10-25 10 33 03](https://cloud.githubusercontent.com/assets/10773353/19673583/cf48d3c0-9a9e-11e6-8dde-67b0d6d03e23.png)
![screenshot from 2016-10-25 10 33 53](https://cloud.githubusercontent.com/assets/10773353/19673582/cf159a3c-9a9e-11e6-9220-03ea7ea2f8f8.png)

**Comment by jsroyal** [comment]
And also xhdpi and hdpi and below images are just don't have qualalty.

**Comment by romannurik** [comment]
This is working as intended. You shouldn't have a lot of text in icons..

**Comment by jsroyal** [comment]
@romannurik But how can we text font size decrease? There is no option here?
