### ISSUE TITLE
Removes transparency

### ISSUE THREAD

**Issue by Stormalv** [romannurik/AndroidAssetStudio#113]
This generator is awesome, but it seems to add a white background where there was transparency before, in the PNG that I use. 

After downloading the generated files, I tried deleting this white background in the Paint.NET program, but that just made the background black, with thin white strips on the edges (that's how it appears when I test it on my phone, at least)

Any idea on what's wrong?

**Comment by romannurik** [comment]
Hey there, can you share an example PNG file that shows the problem?
