### ISSUE TITLE
ask name before create

### ISSUE THREAD

**Issue by jjorian** [romannurik/AndroidAssetStudio#114]
thanks from good tools and this is great.
i am using from this in two last years and always have a problem!!!
1-if ask file name before make download is great 
2-and folder names be base  android studio folder names:
drawable-hdpi
drawable-mdpi
drawable-xdpi
drawable-xxdpi
drawable-xxxdpi

because always we must change file names in ever folder and one to one copy to this folders

thanks a lot from this

**Comment by romannurik** [comment]
Is this for launcher icons? What other name would you need to use?

**Comment by jjorian** [comment]
many times i use from this for another icones for example sider menu icon items for 5 size
ico_home
ico_startwork
ico_about , ............
i want when download icon be optional that ask export file name

**Comment by romannurik** [comment]
For non-launcher icons, you can use the generic icon generator tool
