### ISSUE TITLE
Add support for Android 7.1 round launcher icons

### ISSUE THREAD

**Issue by paolorotolo** [romannurik/AndroidAssetStudio#115]
On Launcher Icon Generator, it would be cool to add support for circular icons too.
In this way, the final zip should include both the ```ic_launcher``` icon and the ```ic_launcher_round``` one.

https://developer.android.com/about/versions/nougat/android-7.1.html#circular-icons

**Comment by romannurik** [comment]
I think it's easier to actually just run the generator twice, once with your normal shape, once with the circle shape. Don't think we want to automatically choose circle parameters for you..

**Comment by paolorotolo** [comment]
So you may want to allow changing name for Launcher Icons. :)

**Comment by paolorotolo** [comment]
For example, having 2 different icon picker in one single page that exports a single zip with both files.
Just a quick draft I made in GIMP:
![assetstudio](https://cloud.githubusercontent.com/assets/5623301/21582095/06ca883e-d04b-11e6-8c18-1cc81771c0d5.png)
