### ISSUE TITLE
Android Asset Studio Desktop Apps

### ISSUE THREAD

**Issue by abuhenasobuj** [romannurik/AndroidAssetStudio#117]
![Android Asset Studio Desktop Apps](https://download-codeplex.sec.s-msft.com/Download?ProjectName=androidassetstudio&DownloadId=1630086&Build=21031) 
# **Android Asset Studio Desktop Apps**
![Android Asset Studio Desktop Apps](http://download-codeplex.sec.s-msft.com/Download?ProjectName=androidassetstudio&DownloadId=1630092)

Long days ago I was thought if is there available a desktop software like this, it would have been very good.

Finally In 2017 - We'll build Android Asset Studio Desktop Apps using existing Android Asset Studio Web Components with **CefSharp**. And It's working Offline.

### [Download for Windows 32 bit](https://androidassetstudio.codeplex.com/)

**Comment by romannurik** [comment]
Cool project! Do you have a GitHub URL I can link to?

**Comment by abuhenasobuj** [comment]
Sir, I'm glad to see you comment. 
And I'll be glad if you add this link for Download the Software on [Website](http://romannurik.github.io/AndroidAssetStudio/) & in [Readme](https://github.com/romannurik/AndroidAssetStudio/blob/master/README.md) file. Or I do add & create an pull request?
> https://androidassetstudio.codeplex.com/

Another request, I need your mail address, I want to share a plan with you.

**Comment by romannurik** [comment]
Hey there, a pull request to add it to the README would be great!

**Comment by abuhenasobuj** [comment]
Sir, Would I commit this?
![screenshot_2017 01 16_23h30m45s_001](https://cloud.githubusercontent.com/assets/16954436/21993217/e89abe38-dc43-11e6-8a40-b033babf10db.png)

**Comment by romannurik** [comment]
I'll add a separate "Related projects" header now.

**Comment by abuhenasobuj** [comment]
That looks good. :+1:

**Comment by abuhenasobuj** [comment]
Wow, New Version Android Asset Studio Looks Pretty So Much Good, Thousand of Love for you  💟

**Comment by abuhenasobuj** [comment]
@romannurik Sir,
I need your help to show the Google fonts offline.
