### ISSUE TITLE
Launcher icon generator doesn't work

### ISSUE THREAD

**Issue by radefffactory** [romannurik/AndroidAssetStudio#124]
Launcher icon generator doesn't work on Windows 7, Firefox browser. When I try to select image from Clipart or from my PC, nothing is happening.
![capture](https://cloud.githubusercontent.com/assets/12969960/22027651/2cb2aa24-dcdd-11e6-97be-a76e3c31d3e0.PNG)

**Comment by romannurik** [comment]
Can you open up the developer console in Firefox (is it Ctrl+Shift+K?) and see if there are any errors?

**Comment by radefffactory** [comment]
This is what is see
![capture](https://cloud.githubusercontent.com/assets/12969960/22027940/2220fb6e-dcde-11e6-8e11-b3bbd565d9c4.PNG)

**Comment by romannurik** [comment]
Ah yes, that's right. I think we're waiting on Firefox 51 or 52 to fix a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1307740).

**Comment by romannurik** [comment]
Yep, I can confirm this works in Firefox 51 beta.

**Comment by radefffactory** [comment]
OK, I'll wait for the update. Thank you! :)
