### ISSUE TITLE
Match launcher icon shadow parameters to shadow values in real icons

### ISSUE THREAD

**Issue by romannurik** [romannurik/AndroidAssetStudio#125]
Currently the launcher icon shadow is a bit blurrier and less opaque than Google apps' launcher icons.

**Comment by rpattabi** [comment]
As per the UI terms, is this bug for "Elevation" or "Cast Shadow" or both?

**Comment by romannurik** [comment]
This is specifically for the drop shadow on the entire shape, not the inner shape. So it affects all icons generated by the launcher icon tool. It's pretty subtle though, so not super high priority.

**Comment by rpattabi** [comment]
By "drop shadow on the entire shape", I think you mean that this subtle bug is for "Elevation". Thanks for the clarification.
