### ISSUE TITLE
No 'Access-Control-Allow-Origin' does not let site render properly

### ISSUE THREAD

**Issue by PrashamTrivedi** [romannurik/AndroidAssetStudio#126]
Chrome Version : 55.0.2883.87 m
Os : Windows 7

![image](https://cloud.githubusercontent.com/assets/972422/22028747/343948d6-dcfe-11e6-912e-132bad46c1d0.png)

1. Clipart icons are not rendered correclty 
2. It looks like some placeholder text (or hover effect texts) are shown. 

Console shows following error.

Access to Font at 'http://fonts.gstatic.com/s/materialicons/v19/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2' from origin 'http://romannurik.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://romannurik.github.io' is therefore not allowed access.

**Comment by romannurik** [comment]
Is this still happening? I can't reproduce this, and curl'ing that URL doesn't hit me with any CORS restrictions. My guess is this was a transient server issue. Please comment if this is still occurring.

**Comment by tarzasai** [comment]
still happening to me...

**Comment by romannurik** [comment]
Do you have a proxy server set up? (Asking per this FAQ):

https://developers.google.com/fonts/docs/troubleshooting#missing_cross-origin_resource_sharing_cors_response_header

**Comment by tarzasai** [comment]
At workplace I'm behind a firewall, but on the previous version I didn't have this issue. On mobile is ok BTW.
