### ISSUE TITLE
Selecting from cliparts doesn't select

### ISSUE THREAD

**Issue by Odaym** [romannurik/AndroidAssetStudio#128]
Hi Roman, great job with the website and I love the new look. However it seems I am unable to get Cliparts to select any of the choices. I search for what I want and I select it, it highlights, but it doesn't get printed to the center of the screen so I can see how to color it or change it in any way. I also try to Download and end up with an empty file.

This happens when whether I'm in Launcher Icon Generator or Action bar/tab Generator

**Comment by romannurik** [comment]
Can you share the following:

- a screenshot
- your browser and OS version
- any errors that appear in the JavaScript console of your browser

**Comment by Odaym** [comment]
Screenshot: http://i.imgur.com/nPoTdln.png

Browser version: **Version 55.0.2883.95 (64-bit)**
OS version: **10.11.4 (OSX El Capitan)**

JavaScript console: http://i.imgur.com/cMJlS7g.png

**Comment by romannurik** [comment]
Hm, I have no clue :-/ can you try clearing your browser cache and refreshing? Also try in Safari maybe?

**Comment by romannurik** [comment]
Oh also do you have the 'material icons' font installed? if so, try removing it.

**Comment by Odaym** [comment]
I tried on another browser yesterday and it's working just fine, the issue was just element blockers I had installed as extensions on Chrome, for ads, disable them and it works fine

**Comment by romannurik** [comment]
Alright thanks!
