### ISSUE TITLE
Setting backgroud color to transparent makes the whole image transparent

### ISSUE THREAD

**Issue by ile** [romannurik/AndroidAssetStudio#129]
This is strange behaviour (see title).

I think it should work like this: If I have a png image that has some transparency and I set the background color to transparent, I would expect that transparency in the image to be retained. 

What happens instead: the image disappears (turns transparent).

**Comment by romannurik** [comment]
Can you share a screenshot?

**Comment by ile** [comment]
The behaviour can be seen with the clipart images that are there by default.

The problem is that the image disappears completely.

**Comment by romannurik** [comment]
Is this for the generic icon generator?

**Comment by ile** [comment]
I should have said that it's for launcher icon generator: https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html

**Comment by romannurik** [comment]
Ah I see. The alpha slider isn't present, but you can still get into a state where you set the transparency.
