### ISSUE TITLE
no rounded corners in exported icons

### ISSUE THREAD

**Issue by UsmanGhauri** [romannurik/AndroidAssetStudio#131]
After exporting i saw that i applied rounded corners to icon and its not being clipped to square shape. but it is scaling images to different sizes

**Comment by romannurik** [comment]
Can you attach a sample output PNG?

**Comment by romannurik** [comment]
closing until more info provided

**Comment by UsmanGhauri** [comment]
i tried now again and its fixed now. it was doing it for specific image not any other image. but now its fixed somehow. thanks 👍
