### ISSUE TITLE
Incorrect transparency

### ISSUE THREAD

**Issue by YuriyGrishin** [romannurik/AndroidAssetStudio#132]
Hello

In categories
 https://romannurik.github.io/AndroidAssetStudio/icons-generic.html
 https://romannurik.github.io/AndroidAssetStudio/icons-actionbar.html
The generated png-files did not have transparency if you choose color with alpha. Just only xxxxhdpi have transparency. 

Sorry for my English.

**Comment by romannurik** [comment]
Good catch, thanks!
