### ISSUE TITLE
Generic icon generator with Image doesn't work

### ISSUE THREAD

**Issue by FranSalguero** [romannurik/AndroidAssetStudio#133]
Hi, new design looks great, but I have the following problem in Generic icon generator and Action bar/tab icon generator:
When trying to generate an icon from a png, it just take the "shape" of the image, even if color is set to transparent.
![captura de pantalla 2017-01-19 a las 16 29 19](https://cloud.githubusercontent.com/assets/12954825/22112764/8017c20c-de64-11e6-8620-ce9216e7be69.png)

**Comment by romannurik** [comment]
Fixed in ce88e24813f6cf9ae1cbff05e5dc2758bd0f7cfb
