### ISSUE TITLE
What about Helvetica

### ISSUE THREAD

**Issue by indywidualny** [romannurik/AndroidAssetStudio#138]
I'm pretty sure when I was using the tool last time I could choose Helvetica as font. Now there're a lot of cool fonts but no Helvetica there. Isn't it possible to bring it back somehow?

**Comment by romannurik** [comment]
Good point, right now it only allows what's in Google Fonts but it's better to allow default web fonts too.

**Comment by romannurik** [comment]
Dup of #149
