### ISSUE TITLE
[Launcher icon generator] SVG images scaled/trimmed/positioned incorrectly

### ISSUE THREAD

**Issue by ananthp** [romannurik/AndroidAssetStudio#139]
Launcher icon generator does not place SVG images correctly. However, PNG images with same dimensions are placed correctly.

Here's the launcher icon generated taking an SVG file as input. SVG width, height and viewbox dimensions are 152px X 152px. This should ideally fit properly in the Square keyline shape.
![launcher_svg_square_4x](https://cloud.githubusercontent.com/assets/494398/22403295/db65bfe8-e638-11e6-9f30-9fcdaf053637.png)

Launcher Icon Generator Settings:
Trim whitespace: `Trim`
Padding: `0`
Scaling: `Crop`
Shape: `Square`

Instead, if we use the PNG export of the same SVG using inkscape (size: same 152px square) with same settings in launcher icon generator
![launcher_png_square_4x](https://cloud.githubusercontent.com/assets/494398/22403332/cf2e4c44-e639-11e6-9f0a-72c6e337b9a7.png)

Same in case of other shapes:

Tall rect launcher icon generated from SVG:
![launcher_svg_tall_rect_4x](https://cloud.githubusercontent.com/assets/494398/22403340/f2be427c-e639-11e6-8ced-5748ef4c8c2f.png)

The same, generated from PNG:
![launcher_png_tall_rect_4x](https://cloud.githubusercontent.com/assets/494398/22403404/dd314e16-e63b-11e6-857c-4c74b671fcde.png)

I've tried changing the browser (Firefox, Chrome, Chromium) and Inkscape versions used to generate SVG (0.91 and 0.92). The issue exists anyway.

Here are the svg and png source images: [test-images--svg-bug--launcher-icon-generator.zip](https://github.com/romannurik/AndroidAssetStudio/files/737435/test-images--svg-bug--launcher-icon-generator.zip)

**Comment by ananthp** [comment]
Same issue can be seen if we manually import svg from Google material icons.

**Comment by romannurik** [comment]
Thanks for the detailed report!
