### ISSUE TITLE
[Launcher icon generator] SVG images are not upscaled correctly

### ISSUE THREAD

**Issue by ananthp** [romannurik/AndroidAssetStudio#140]
Try:

* Download a 48px material icon SVG from https://github.com/google/material-design-icons
* Load it in Launcher icon generator

Notice:
1. The icon is not scaled/positioned properly #139 
2. The icon is blurry in 512px (web) and other high resolutions

![image](https://cloud.githubusercontent.com/assets/494398/22403567/34a671c6-e641-11e6-8072-6fc3943c7c27.png)

According to Material Design guidelines, product icons are 48dp square. In SVG it can be modelled as 48px square (1:1 unit grid) or 192px (4:1 unit grid). These two dimensions are common in icon design. However, neither svg images using 1:1 unit grid nor 4:1 grid work well with Launcher icon generator, because they are probably rendered as bitmap at 48px or 192px resolution respectively and scaled up to 512px (for web) causing the blur.

**Comment by romannurik** [comment]
Good catch. This is a regression from the old asset studio I think. Should definitely fix this.
