### ISSUE TITLE
Background Color issue

### ISSUE THREAD

**Issue by menna-ali** [romannurik/AndroidAssetStudio#142]
I think there is a bug with transparent background color in the icon generator. When I upload a .png with a transparent background and I try to create an icon with a transparent background as well, the light and dark transparent values are not correct. This is the rgba value I get for light transparent color rgba(96, 125, 139, 0). The icon shows a blueish background though.

**Comment by romannurik** [comment]
Can you share a screenshot?

**Comment by menna-ali** [comment]
I solved the problem. Turns out I never set the shape to none. Thank you!
