### ISSUE TITLE
SVGs without width and height set don't load property

### ISSUE THREAD

**Issue by rarcher** [romannurik/AndroidAssetStudio#144]
Attempting to use the "Launcher icon generator" > "Foreground" > "Image" option to load an SVG file causes this to happen:
![load issue](https://cloud.githubusercontent.com/assets/9158042/22732376/f5e0f42a-edbb-11e6-8294-bbfacdff9d47.png)
The file loaded is a [stock icon, downloaded from the Noun Project](https://thenounproject.com/term/question/680369/).  This screenshot shows the generated icon's web version, but all versions have the same distorted graphic.

I'm using Chrome on Ubuntu Linux, if it matters.

**Comment by romannurik** [comment]
This is caused when the `<svg>` has no `width` and `height` set, but does have a `viewBox` set. I don't see an immediate quick fix, but a workaround is to edit the SVG to include width and height.

**Comment by romannurik** [comment]
Bug for reference:
https://bugs.chromium.org/p/chromium/issues/detail?id=475009

**Comment by rarcher** [comment]
Workaround confirmed to work.

For those unfamiliar with editing SVG graphics, the procedure is:
1. Open the SVG in a text editor.
2. You will see a bunch of XML.  Locate the attribute "viewBox" in the parent element, which should have a series of four numbers set as its value.
3. Add a "width" attribute to the parent element.  Set its value to the third number in the "viewBox" attribute.
4. Add a "height" attribute to the parent element.  Set its value to the fourth number in the "viewBox" attribute.
5. Save your changes.

The SVG should now render correctly in Android Asset Studio.

**Comment by romannurik** [comment]
Fixed probably a while ago
