### ISSUE TITLE
Microsoft Edge download zip button

### ISSUE THREAD

**Issue by brunomassa** [romannurik/AndroidAssetStudio#145]
Hi when i try to download a icon the website not generates a zip file only generates a txt file.

Thanks.

**Comment by danielpetrica** [comment]
@brunomassa That's because Edge (which it's basically a costumed internet explorer, why don't you change it?) don't know how to save a file properly.
Go to the downloaded file in the download folder and add ".zip" to the end of his name.

**Comment by brunomassa** [comment]
Thanks 👍

**Comment by romannurik** [comment]
Not officially supporting Edge
