### ISSUE TITLE
How is font/text dynamically resized

### ISSUE THREAD

**Issue by MSIH** [romannurik/AndroidAssetStudio#146]
Where in the code is font/text dynamically resized?

In the code below from app/scripts/studio/forms/ImageField.js 

the ctx.font , the font size is ${textHeight}px/${size.h}px , but both of these are fixed values, so should not change based number of characters.

```
case 'text':
          var size = { w: 6144, h: 1536 };
          var textHeight = size.h * 0.75;
          var ctx = imagelib.Drawing.context(size);
          var text = this.textParams_.text || '';
          text = ' ' + text + ' ';

          ctx.fillStyle = '#000';
          ctx.font = `bold ${textHeight}px/${size.h}px ${this.textParams_.fontStack}`;
          ctx.textBaseline = 'alphabetic';
          ctx.fillText(text, 0, textHeight);
          size.w = Math.ceil(Math.min(ctx.measureText(text).width, size.w) || size.w);

          resolve({ctx, size});
          break;
```

**Comment by romannurik** [comment]
The text is first rendered to an offscreen buffer by ImageField, and the each generator (e.g. the launcher icon generator) calls drawCenterInside or drawCenterCrop to fit the rendered text into the desired space.
