### ISSUE TITLE
Loading SVGs when needed

### ISSUE THREAD

**Issue by treisska** [romannurik/AndroidAssetStudio#15]
I don't think that loading a lot of SVGs is a good idea. Firefox is currently using 3Gb of RAM for this page only, that's ridiculous.

**Comment by SuicSoft** [comment]
@treisska Over a year late, but it only takes 200mb on Chrome / Chromium on Linux with 6GB RAM

**Comment by romannurik** [comment]
Now uses the iconfont, so this is fixed.
