### ISSUE TITLE
Launcher Icon Generator - add option to generate mipmap

### ISSUE THREAD

**Issue by panell** [romannurik/AndroidAssetStudio#150]
So we should be able to select between drawable and mipmap (this should be default, because mipmaps are not pruned from the APK when APK split is enabled - custom launcher may use different size of icon then system size).

Image is generated in the same way, but names of zip file are different
drawable-hdpi
drawable-mdpi
drawable-xhdpi
drawable-xxhdpi
drawable-xxxhdpi

or

mipmap-hdpi
mipmap-mdpi
mipmap-xhdpi
mipmap-xxhdpi
mipmap-xxxhdpi

**Comment by romannurik** [comment]
Why would you need to generate a launcher icon that's NOT in mipmap-xx folders?

**Comment by panell** [comment]
You are right, so just change it to mindmap

**Comment by romannurik** [comment]
It's already mipmap :)
