### ISSUE TITLE
Icon rv_hookup shown twice

### ISSUE THREAD

**Issue by mueller-ma** [romannurik/AndroidAssetStudio#152]
![rv_hookup](https://cloud.githubusercontent.com/assets/22525368/24582663/8c563a04-1734-11e7-8173-a8e24861e2b6.JPG)
My user agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by romannurik** [comment]
should no longer be the case
