### ISSUE TITLE
Transparent Background not working

### ISSUE THREAD

**Issue by joshuatam** [romannurik/AndroidAssetStudio#153]
Transparent Background not working, showing a blue color `#607d8b`

**Comment by SolveSoul** [comment]
I'm still having this issue. Any known fixes?

**Comment by johnjohndoe** [comment]
Has this been fixed? The preview color of the clipart ...

![low-transparency](https://user-images.githubusercontent.com/144518/52911607-47ad2400-32a6-11e9-883e-10ad1014dc83.png)

... becomes **darker** the more I **increase the transparency**.

![high-transparency](https://user-images.githubusercontent.com/144518/52911605-47148d80-32a6-11e9-93b1-880676d1a972.png)
