### ISSUE TITLE
Download directly from url

### ISSUE THREAD

**Issue by x011** [romannurik/AndroidAssetStudio#157]
Hi there,
Is it possible to specify all arguments on the url and force the download of the assets?

> romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=text&foreground.text.text=&foreground.text.font=&foreground.space.trim=1&foreground.space.pad=0.25&foreColor=rgba(96%2C%20125%2C%20139%2C%200)&backColor=rgb(68%2C%20138%2C%20255)&crop=0&backgroundShape=square&effects=none&name=ic_launcher&**SOME_ARGUMENT_HERE** ?

PS: Thank you for this project, it's very helpful.

**Comment by romannurik** [comment]
if the intent is to use this as part of a build process, unfortunately no, everything is done in the browser.
