### ISSUE TITLE
1024px size

### ISSUE THREAD

**Issue by fquirogam** [romannurik/AndroidAssetStudio#159]
Hi, I'm trying the online version and it works awesome, the only problem is that the high resolution icon is 512x512 but in ionic I need a 1024x1024px image to create all icons.

**Comment by renanmedina** [comment]
I have already implemented this feature on my local copy. I'll make a pull request for the repository owner so he can evaluate to merge and you can use this feature.

**Comment by momentumcode** [comment]
@romannurik This would be super useful as the Facebook for Developers portal requires a 1024x1024px icon to be uploaded.

**Comment by snowdream** [comment]
@romannurik It is a  useful feature.

**Comment by borgogelli** [comment]
+1. Please make a pull request

**Comment by GioPan04** [comment]
+1 It's a useful feature

**Comment by GioPan04** [comment]
I resolved cloning this repo and searched for 512 in the code and replaced with 1024, and it worked!

**Comment by caoyanglee** [comment]
I need 1024x1024 icon🥺
and with shadow~

**Comment by martin-braun** [comment]
4 years ... anyways, I had to do something about it.

**Comment by martin-braun** [comment]
Unfortunately, @romannurik rejected [my PR](https://github.com/romannurik/AndroidAssetStudio/pull/242) that would enable 1024px size icons in the export. You can learn more about the reason on the PR itself.

**Comment by romannurik** [comment]
Closing in favor of discussion in #242
