### ISSUE TITLE
Add option to add second line in Text icon

### ISSUE THREAD

**Issue by prateekjaiswal** [romannurik/AndroidAssetStudio#163]
I really love the tool and really appreciate effort you guys put in. It would be more useful if i have second line in text logo. Many application have long name e.g. "Diamond Crush" and that name doesn't fit in single line. 

I am also a developer, If someone can guide me i can also do it.

Rerefence : [https://www.norio.be/android-feature-graphic-generator/](https://www.norio.be/android-feature-graphic-generator/)

**Comment by romannurik** [comment]
Duplicate of #33
