### ISSUE TITLE
Clipart icons displayed incorrectly

### ISSUE THREAD

**Issue by dant3** [romannurik/AndroidAssetStudio#164]
Environment: Ubuntu 16.04, Google Chrome 58.0.3029.110 (64-bit)

I can't see any errors in networking & console. If there anything else I can share let me know.
In Firefox it works as expected.

![image](https://user-images.githubusercontent.com/820057/27006095-c08e9f0a-4e34-11e7-9ecf-d2ae0b0f4e7e.png)

**Comment by romannurik** [comment]
Looks like the material icon font isn't loading. Make sure you don't have it locally installed, or try a hard browser refresh. Guessing other sites that use the icon font also wouldn't load.
