### ISSUE TITLE
White squares instead icons. [Notification Icon Generator]

### ISSUE THREAD

**Issue by e16din** [romannurik/AndroidAssetStudio#167]
**Image:** png, 256x256, transparent background.

**Screenshot:** https://yadi.sk/i/4BpMgwMm3KUvWk

**Comment by romannurik** [comment]
You need to provide icons with transparency. The color data is discarded for notification icons

**Comment by e16din** [comment]
What does it mean? I use png with transparency.
Can you describe more specifically?

**Comment by jkasten2** [comment]
@e16din You need to edit your icon by drawing a 100% transparent outline to define the shape of it. See Google Material design icons for some examples.
https://material.io/icons/
