### ISSUE TITLE
iOS and UWP Export

### ISSUE THREAD

**Issue by junian** [romannurik/AndroidAssetStudio#169]
Hello,

Thank you for the great work for this project. It's really helpful.
I have a question. It's silly actually because it's called `Android Asset Studio` for an obvious reason.
But, I'd like to know if you have any plan to add iOS and UWP assets? If so, I would love to give pull request for that.

If not, I plan to make a new project on top of this fork.

Best regards,

Junian

**Comment by romannurik** [comment]
I'd suggest forking the repository or just borrowing code to make a new tool, as iOS feels out of scope for this project.

**Comment by junian** [comment]
@romannurik Thank you for the answer. Really appreciate it.
