### ISSUE TITLE
Integrate electron packager

### ISSUE THREAD

**Issue by sobujbd** [romannurik/AndroidAssetStudio#171]
Could you produce app like MaterialColorsApp

**Comment by romannurik** [comment]
I thought about this a while ago, I don't think it's worth the maintenance burden for me to build it but I welcome contributions or forks 😁

**Comment by sobujbd** [comment]
I forked, could you configure it. I will try to maintenance it with your updates.

**Comment by sobujbd** [comment]
Recently I tried with [electron-quick-start](https://github.com/electron/electron-quick-start)

But got this log:
```
spectrum.js:16 Uncaught ReferenceError: jQuery is not defined
    at spectrum.js:16
    at spectrum.js:18
app.js:5 Uncaught ReferenceError: $ is not defined
    at Object.28.../../imagelib (app.js:5)
    at s (app.js:1)
    at app.js:1
    at Object.31../BooleanField (app.js:5)
    at s (app.js:1)
    at app.js:1
    at Object.32../Hash (app.js:5)
    at s (app.js:1)
    at app.js:1
    at Object.10.../imagelib (app.js:2)
icons-launcher.html:2 Uncaught ReferenceError: pages is not defined
    at icons-launcher.html:2
```
![androidassetstudio-electron-app](https://user-images.githubusercontent.com/16955338/29667073-d27f621e-88fc-11e7-94fc-e3750a1e6368.png)
