### ISSUE TITLE
lanucher icon can not center

### ISSUE THREAD

**Issue by huajianjiang** [romannurik/AndroidAssetStudio#173]
![ic_my_wifi](https://user-images.githubusercontent.com/12984573/29739154-bdb5fc08-8a69-11e7-8dac-aaddd6b97974.png)

**Comment by mayanxoni** [comment]
Yeah, that has happened to me before.

**Comment by ishitatsuyuki** [comment]
I have also experienced this when using a SVG.

**Comment by Sakib-Rahman-Bangladesh** [comment]
I'v faced the same.

**Comment by renanmedina** [comment]
Can you provide the image you're using to generate your icon ? I would like to reproduce this problem and fix it. Thank you!

**Comment by Sakib-Rahman-Bangladesh** [comment]
Quick reply: 
I solved my problem, but for better outcome i'll provide you image, during my project upgrade time.

Thanks for your collaboration.

**Comment by romannurik** [comment]
Duplicate of #174
