### ISSUE TITLE
Add ability to change text color

### ISSUE THREAD

**Issue by martinomburajr** [romannurik/AndroidAssetStudio#176]
There is currently no ability to change the texts color. It seems to only allow black text.

![image](https://user-images.githubusercontent.com/8682597/33552425-e4ec9b34-d905-11e7-8958-f2186afadddc.png)

**Comment by romannurik** [comment]
You just need to change the Color field to a non-transparent color

**Comment by martinomburajr** [comment]
Thanks for the swift response!
