### ISSUE TITLE
Getting only blank images

### ISSUE THREAD

**Issue by ednonunes** [romannurik/AndroidAssetStudio#177]
Hello,

Im getting only blank images when generating the notification icons.
Using Google Chrome, sending an image with 50kb (PNG). 
Can anyone help?

Thanks 

![captura de tela 2018-01-04 as 11 31 54](https://user-images.githubusercontent.com/10046732/34565860-9a1cc6c8-f143-11e7-8bcd-5fda69caf917.png)

**Comment by romannurik** [comment]
This is working as intended. The source image needs to have alpha transparency. All color in the image is replaced with white, since status bar icons on Android are colored automatically by the system.
