### ISSUE TITLE
How to create Notification icon using AndroidAssetStudio

### ISSUE THREAD

**Issue by vijaypwr61** [romannurik/AndroidAssetStudio#178]
Hi, I have my own icon image designed in Inkscape. I have different density imgaes (6dpi,12dpi,24dpi,48dpi,72dpi,96dpi,150dpi,300dpi). I tried Android Asset Studio to generate launcher icon I got it perfectly what I need but when I tried to get notification icon, it is not showing any image which I upload from my own icon (pc) with different density images.

So how to get notification icon from own image?

here is my own logo

![ls_12dpi](https://user-images.githubusercontent.com/25868370/34902094-78699670-f83a-11e7-9014-c9fa0cee0501.png)

**Comment by joeyscarim** [comment]
Same issue for me.

Cannot upload to Notification icon generator.

**Comment by hegelstad** [comment]
Notification Icons must be GREYSCALE and/or transparent only since Lollipop 5.0.

AndroidAssetStudio is not able to convert your picture into greyscale/transparent..
