### ISSUE TITLE
How to create Notification icon using AndroidAssetStudio?

### ISSUE THREAD

**Issue by vijaypwr61** [romannurik/AndroidAssetStudio#179]
Hi, I have my own icon image designed in Inkscape. I have different density imgaes (6dpi,12dpi,24dpi,48dpi,72dpi,96dpi,150dpi,300dpi). I tried Android Asset Studio to generate launcher icon I got it perfectly what I need but when I tried to get notification icon, it is not showing any image which I upload from my own icon (pc) with different density images.

So how to get notification icon from own image?

here is my own logo

![ls_12dpi](https://user-images.githubusercontent.com/25868370/34902133-37b979a0-f83b-11e7-8eb1-669470e5032e.png)

**Comment by romannurik** [comment]
Notification icons don't have any color, so you need to provide an image with transparency (i.e. not a rounded rectangle shape).
