### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by tesoner** [romannurik/AndroidAssetStudio#189]
Is this project abandoned?

**Comment by Angelk90** [comment]
@romannurik : Are there any news about the project?

**Comment by tes1oner** [comment]
@Angelk90 Are you interested in contributing to the development?

**Comment by MichaelPriebe** [comment]
Looks abandoned.

**Comment by romannurik** [comment]
Very, very minor maintenance intended going forward... I don't plan on developing this tool much further. e.g. I don't think I'll ever get to supporting adaptive icons. The tooling built into Android Studio is pretty great these days :)

**Comment by NatoBoram** [comment]
The tooling built into Android Studio doesn't support SVG files nor Clip Art, I don't think it's "great".

![image](https://user-images.githubusercontent.com/10495562/52170047-6d67f400-2710-11e9-8ce7-05bcb0546e3d.png)

**Comment by MichaelPriebe** [comment]
It actually does support SVG. But I just don't like it shoehorned into Android Studio

**Comment by NatoBoram** [comment]
Can you fill me up on how to generate adaptive + legacy icons with an SVG foreground?
