### ISSUE TITLE
update to latest list of material icons (including achievements icon)

### ISSUE THREAD

**Issue by agneng** [romannurik/AndroidAssetStudio#192]
please add support for achievement icon.

**Comment by romannurik** [comment]
i think in general the list of material icons needs an update

**Comment by romannurik** [comment]
I don't see an "achievements" icon [here](https://material.io/tools/icons/?search=achieve&style=baseline). Which achievements icon are you referring to?

**Comment by agneng** [comment]
![81527-200](https://user-images.githubusercontent.com/36489581/42842553-2e2918d8-8a16-11e8-9b49-42574e3f2f88.png)
like this one :-)

**Comment by romannurik** [comment]
Hm, where did you see that one? I don't see it in the material iconfont

**Comment by agneng** [comment]
just a simple google search , i found it on "Noun Project". I sent it to give you idea what i am talking about.

**Comment by romannurik** [comment]
Ah I see. For anything not in the Material Icons list, you can just drag any SVG from your desktop instead of using the clipart feature.
