### ISSUE TITLE
Make only lower case names possible for the icon name

### ISSUE THREAD

**Issue by uWinkel** [romannurik/AndroidAssetStudio#194]
React native will you an error when building the app otherwise

**Comment by romannurik** [comment]
Sorry, going to close this out since the Android SDK does support uppercase values. If this becomes more of a problem we could just show a warning when using uppercase in the generators.

**Comment by uWinkel** [comment]
You could add text with `helpText: 'Only use lower case letters'` when creating the Textfield [here](https://github.com/romannurik/AndroidAssetStudio/blob/0378fd21d8fae127de413fe121c836ee804c59f6/app/pages/launcher-icon-generator.js#L125) 

Or even add input validation with either jquery or css. This has cost me some time to debug so will try to create a pull request for this tomorrow ;)
