### ISSUE TITLE
Allow me to generate a blank icon by simply setting the color

### ISSUE THREAD

**Issue by marcushasfun** [romannurik/AndroidAssetStudio#195]
Currently, the only way to generate a blank placeholder icon, e.g a green square, is to choose the image option and load a PNG. I'd like to be able to select no source and just set the color to what I need.

**Comment by romannurik** [comment]
Thanks for the discussion all! I don't see much value in doing something specifically for this, but I love the idea of the workaround suggested as a way to do this when needed.
