### ISSUE TITLE
Request: allow to auto-shrink

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [romannurik/AndroidAssetStudio#199]
Sometimes the input image already has duplicate pixels, and we wish to have it minimal, to adjust to the content.

Could be nice to have an auto-shrink button, to have the image minimized to what it could be.

**Comment by romannurik** [comment]
Sorry I never replied -- pretty sure this already exists in the tool..

**Comment by AndroidDeveloperLB** [comment]
@romannurik In what tool? Can you please demonstrate (video) how it's done?
I never saw this behavior you say that exists, anywhere.

**Comment by romannurik** [comment]
I'm referring to the "Trim stretch region" button on the bottom:

Before:
![before](https://user-images.githubusercontent.com/100155/132350243-3b0a98d9-fe0c-4763-8fb7-2cc194689d1b.png)

After:
![after](https://user-images.githubusercontent.com/100155/132350347-d7ecaca7-6c91-4a1e-8f05-a4e3c6b300e2.png)

Were you referring to something else?

**Comment by romannurik** [comment]
Also if you do "Auto-stretch" it will try to optimize the corners... so Auto-stretch + Trim stretch region gives you something pretty minimal:

![optimized](https://user-images.githubusercontent.com/100155/132350558-2defe371-9084-41f8-8fd9-f9d0a2527568.png)

**Comment by AndroidDeveloperLB** [comment]
You mean here:

https://romannurik.github.io/AndroidAssetStudio/nine-patches.html#&sourceDensity=320&name=example

Doesn't seem like it works.
It seems to have multiple issues (Chromium based web browser):

1. The preview shows the black markings.
2. The dotted lines don't seem to match any markings. Not sure what they mean this way, and why they are positioned out of place.
3. Using "Trim stretch region", it didn't the size of the marking size at all. Instead it seems that it moved it, and I think it reduced the size of the image in other places. The dotted lines still seem weird after using it, too. 
4. Choosing "auto stretch" (after "trim stretch region"), it doesn't seem to do anything except moving the dotted lines, and then they still seem out of place.
5. There is no status bar (or anything similar) on this tool showing the size of the 9-patch (pure resolution of the PNG file), so I can't know for sure what's going on. I also can't see where the cursor is located in real time (to see where each pixel/marking went).
6. And most importantly: Choosing to download (I wanted to see for myself in an editor what it did), it doesn't do anything.

Attached files of all the above, including the original 9-patch file that I tried to play with.

[files.zip](https://github.com/romannurik/AndroidAssetStudio/files/7123052/files.zip)

**Comment by romannurik** [comment]
Oh it looks like you're uploading an existing nine-patch ... the tool isn't a nine-patch EDITOR so much as a GENERATOR... i.e. it won't let you edit an existing nine-patch, but if you just drop in something like this PNG, it'll generate the nine-patch markings for you after you resize the stretch regions and such.
![Artboard](https://user-images.githubusercontent.com/100155/132555807-9db39e46-5081-4ac3-a082-27ab7fabddf6.png)

**Comment by AndroidDeveloperLB** [comment]
@romannurik Are you saying it ignored the markings for some reason? After you generate something with it, you can't edit it again?
Why close the issue, then?

Can you please offer this tool on the IDE itself, too (including editing, and including auto-shrinking) ?
