### ISSUE TITLE
Request:  New Google Play app icon specification

### ISSUE THREAD

**Issue by yoonhok524** [romannurik/AndroidAssetStudio#201]
According to the [Android Dev Blog](https://android-developers.googleblog.com/2019/03/introducing-new-google-play-app-and.html)

The App icon should be changed.

Could you apply this please?

**Comment by yoonhok524** [comment]
@romannurik Why is this closed without any comment?

**Comment by yoonhok524** [comment]
Oh, sorry you already applied it! Thank you~ :)

**Comment by romannurik** [comment]
Yep sorry. Any icon shape should generate a square web icon.
