### ISSUE TITLE
Can't apply cast shadow effect when background none

### ISSUE THREAD

**Issue by bpappin** [romannurik/AndroidAssetStudio#202]
In order to build an adaptive icon, i want to separate the background from the foreground.
I can do that by setting the "shape" to "none" but then I don't have the option to cast shadow.

Can that be added to the tool? 
If that is not possible, it would probably be sufficient to allow me to set the background to transparent.

**Comment by romannurik** [comment]
There's a fork linked in this issue that'll do it: https://github.com/romannurik/AndroidAssetStudio/issues/183

My plan is to eventually make an adaptive icon builder right in this tool :-/
