### ISSUE TITLE
Launcher Icon Generator - Web Image Not working

### ISSUE THREAD

**Issue by RY4N0** [romannurik/AndroidAssetStudio#203]
The 'Web' sized image on the Launch Icon Generator is always appearing a square. It does not reflect any changes that are made and also saves as a square

![web image](https://user-images.githubusercontent.com/49644388/56131481-73cfe300-5f7f-11e9-9956-f3ee3cce7221.jpg)

**Comment by RY4N0** [comment]
Here's another example

![circle](https://user-images.githubusercontent.com/49644388/56131522-8f3aee00-5f7f-11e9-84f6-6b84ed522581.jpg)

**Comment by romannurik** [comment]
Working as intended to accommodate the new Play Store guidelines
