### ISSUE TITLE
Non-9 patch Asset Generation

### ISSUE THREAD

**Issue by mzhukovs** [romannurik/AndroidAssetStudio#206]
First off, thanks for the awesome tools, and the video on working with resources in Android on YouTube. Great stuff!

**A potential enhancement I'd like to suggest** _(let me know if I am missing something, but this doesn't seem to be possible right now, unless you use the launcher icon option with no shape background but the downloaded files appear in mipmap instead of drawable in that case):_

For images that we don't actually want to be stretched in any way, and therefore we set the stretch regions to **zero** on all 4 sides while on the "Stretch region" edit mode, then the resulting asset files should
1) not have the .9 suffix 
2) not have the black lines on the sides

Also, while in that "Stretch region" edit mode, to make this easier, would be nice to have a convenience button in that lower toolbar that says "No Stretch" so user can click that instead of dragging the lines to zero manually.

Thoughts?

**Comment by romannurik** [comment]
Oh so you're looking for a generic image resizing tool? There are several other generators that can do that... Can you be more specific maybe on the use case you're trying to achieve?

**Comment by mzhukovs** [comment]
Thanks for the quick response. And haha yes basically - I just need all the different asset sizes and the image should not be stretched - i did run accross some other ones but didn't think they were as nice as yours and it seemed like being able to do this in your suite of tools would be a nice/easy fit. Do you have one you'd recommend?

**Comment by romannurik** [comment]
This is a dup of #9 ... I'd assume there are lots of more generic tools that can do that, but it's a fair request. (but this is a duplicate so closing this one out)
