### ISSUE TITLE
Does this project embraces Android guidelines?

### ISSUE THREAD

**Issue by MaxInMoon** [romannurik/AndroidAssetStudio#212]
Regarding [icon-design-specifications](https://developer.android.com/google-play/resources/icon-design-specifications), I don't understand why this generator applies down-sizing and radiuses?

**Comment by romannurik** [comment]
The 512px icons generated for Google Play are always full square. The launcher icon generator still generates older-style assets used before adaptive icons became a thing. At some point in the future I'd like to switch to / start supporting adaptive icons, but haven't had any time to tackle that recently.
