### ISSUE TITLE
Use as an api to crop icons?

### ISSUE THREAD

**Issue by mortenholmgaard** [romannurik/AndroidAssetStudio#215]
Do you know of any simple way to use AndroidAssetStudio as a api, to have a CI or local script call and get icons with a predefined set of parameters like in the UI?
I have briefly look at the requests it is not strait forward to figure out a way to call this.

**Comment by romannurik** [comment]
Unfortunately no, but you could theoretically build an API for this that runs on PhantomJS or Puppeteer (headless Chrome). It'd be a ton of work but I think it's doable.
