### ISSUE TITLE
nine-patches view Bug

### ISSUE THREAD

**Issue by gastsail** [romannurik/AndroidAssetStudio#216]
I have a bug where I try to generate nine-patches images for an image with the followin dimensions 1384x349 and the UI moves and place the whole image in the browser but I cant get to see no more the download widget button, it seems the image stretchs and it move the whole view

Photo

https://imgur.com/a/wGHjJEB

**Comment by gastsail** [comment]
I had to shrink the viewport of the browser to fit the whole image

**Comment by romannurik** [comment]
Duping the request to #200
