### ISSUE TITLE
Allow background to be transparent

### ISSUE THREAD

**Issue by think-free** [romannurik/AndroidAssetStudio#217]
Icons for notifications should be white with transparent background.
Had to edit the icons manually

**Comment by romannurik** [comment]
Can you paste a screenshot of what you're seeing? The background for notification icons is already transparent when generated w/ a PNG that uses transparency.

**Comment by MAkbarZ** [comment]
Hi @romannurik.

@think-free is right. "Color" property does allow transparency, but "Background Color" property doesn't allow it.

This first image shows color pallet for Background Color property.
![image](https://user-images.githubusercontent.com/74808265/106359120-63deea00-6332-11eb-8b33-92b9cbfc685e.png)

![image](https://user-images.githubusercontent.com/74808265/106359139-76f1ba00-6332-11eb-9fa5-75df6ffe7416.png)

Overall it is good tool.
Thanks.

**Comment by romannurik** [comment]
The "None" shape was intended to allow transparent icons, but on Android all icons have background shapes now, so need to revisit the None shape per #219
