### ISSUE TITLE
Please add 36 x 36 Icon Support

### ISSUE THREAD

**Issue by SkywolfGameStudios** [romannurik/AndroidAssetStudio#218]
I really appreciate this program, I found it to be extremely helpful for me. However, I use unreal engine 4 for making game projects on Android and there's an extra one in there that is 36 x 36 so I had to manually resize the image for that one therefore I'd like to request to have support for that one added into the downloadable icon pack please and thank you.

Also, do you have somewhere I could donate to you as thanks for making this program? I'd like to donate because this program helped me out a ton to make icons really quickly thank god. I'm more of a 3d Artist and UE4 Indie Developer than I am a graphics artist.

**Comment by martin-braun** [comment]
Unreal Engine also targets iOS, this tool is only for Android. Please read / follow / join the discussion at #242. The idea of this PR is to export the icon in 1024 x 1024 as well. You would then need to feed it into another tool like [App Icon Generator](https://appicon.co/) to get all sizes, including 36 x 36.
