### ISSUE TITLE
Revisit "None" shape (was: Icon is not material flat)

### ISSUE THREAD

**Issue by tapz** [romannurik/AndroidAssetStudio#219]
Why is Effect None still creating raised edges? The icon is not flat as it should be in Material Design.

Also the solid color is messed up.

Per Android icons specifications:

> Shape: Full square – Google Play dynamically handles masking. Radius will be equivalent to 20% of icon size.
> Shadow: None – Google Play dynamically handles shadows. See 'Shadows' section below on including shadows within your artwork.
> After the asset is uploaded, Google Play dynamically applies the rounded mask and shadow to ensure consistency across all app/game icons.
> Utilize the full asset space as the background when dealing with minimalistic artwork.

**Comment by romannurik** [comment]
The "none" shape needs to be fundamentally revisited in light of the adaptive icon changes in the platform...

**Comment by romannurik** [comment]
This shape will be removed, it no longer makes sense w/ adaptive icons.
