### ISSUE TITLE
SVG not showing up correctly

### ISSUE THREAD

**Issue by blackjoe4** [romannurik/AndroidAssetStudio#223]
Using Illustrator to create SVG and tried all versions and settings. But no result. Tried downloading the SVG logo from wikipedia and it turns out like this. But mine does not show ut at alls. Have been forced to use PNG instead.   :(
<img width="146" alt="Screenshot at Jun 24 15-55-41" src="https://user-images.githubusercontent.com/29067525/85570026-5393bd80-b633-11ea-91a3-83c38f2505a2.png">

**Comment by romannurik** [comment]
Hi there, mind attaching the SVG?

**Comment by blackjoe4** [comment]
Sure, that was stupid of me not to attach them directly.

Thanks for looking into this. Tried to get any SVG working and figure out the problem. But i could see anyone else on the forum have the same problem.  :/

[SVG_logo_h.svg.zip](https://github.com/romannurik/AndroidAssetStudio/files/4852756/SVG_logo_h.svg.zip)
[ic_launcher_foreground.svg.zip](https://github.com/romannurik/AndroidAssetStudio/files/4852771/ic_launcher_foreground.svg.zip)

**Comment by romannurik** [comment]
For posterity, when SVGs don't have a `width` and `height`, it doesn't seem to import correctly / can't infer from the viewbox. There's probably a bug somewhere [here](https://github.com/romannurik/AndroidAssetStudio/blob/5ce98e759b421bb575bdba9fb11885436ae01ffc/app/studio/forms/image-field.js#L488) with how we manage natural width/height from SVGs
