### ISSUE TITLE
Multiple line for Text Foreground

### ISSUE THREAD

**Issue by goaldeer** [romannurik/AndroidAssetStudio#226]
Multiple line for Text Foreground isn't working.

**Comment by monsterbrain** [comment]
I think that feature is left out - maybe you could look at this PR. It's working by the way.

[https://github.com/romannurik/AndroidAssetStudio/pull/147](https://github.com/romannurik/AndroidAssetStudio/pull/147)

**Comment by romannurik** [comment]
Yes please take a look at the alternative in that issue
