### ISSUE TITLE
Exported launcher icon has a slight gradient on the top left corner

### ISSUE THREAD

**Issue by gim-** [romannurik/AndroidAssetStudio#234]
### Steps to reproduce
1. Export [this](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=android&foreground.space.trim=1&foreground.space.pad=0.25&foreColor=rgb(255%2C%20255%2C%20255)&backColor=rgb(0%2C%200%2C%200)&crop=0&backgroundShape=square&effects=none&name=ic_launcher) icon, which has full black background color selected.
2. Zoom in and look closely at the top left corner of the exported icon.
<img width="685" alt="Screenshot 2020-10-07 at 09 56 58" src="https://user-images.githubusercontent.com/1240012/95297773-b1b37c00-0883-11eb-8547-7b1c365ceda1.png">

### Expected:
Selected background color.

### Actual:
Unexpected gradient is being added.

**Comment by romannurik** [comment]
This is actually expected behavior for the asset studio, the "None" effect still applies a subtle top-left radial gradient per the [now old] Android icon specs.
