### ISSUE TITLE
Download Zip button issue.

### ISSUE THREAD

**Issue by FinassaR** [romannurik/AndroidAssetStudio#235]
if an image is larger than let's say,  400x.......in width on mobile devices,  the download zip button can't be reached.  I tried changing dpi and even viewed source to find the js script for the download button but it's hidden. Please put the download button in the same area as the file selector. Especially for cases such as this . Or better yet make the 9patch page compatible for mobile browsers at multiple dpis. I'd much rather advise for the download zip button to be relocated.

**Comment by romannurik** [comment]
Hi sorry, can you share a screenshot? And are you using the nine patch generator, or something else?

**Comment by FinassaR** [comment]
Yes it's the 9 patch tool. Here is a screen shot of the issue.  By the way
please don't ever get rid of the tool it's a life saver.

**Comment by romannurik** [comment]
Ah I see the issue (though you didn't attach a screenshot!) I think scrolling in the canvas area is the right solution.

**Comment by romannurik** [comment]
Fixed with 51b91cc4c1b08492fa0d6ade96adb4f33bc76e9e
