### ISSUE TITLE
Launcher icons : support for image asset for background

### ISSUE THREAD

**Issue by adroitandroid** [romannurik/AndroidAssetStudio#248]
Hi Roman, thank you for the tool. we're looking for support for image assets for background in launcher icons. presently on the site we're seeing only color for background. Our visual designers are finding it hard to use Android Studio, with gradle sync issues at times and the import image asset option missing from the list of options at times, they can't independently use Android Studio for this.

If there's a timeline for adding support for images as background in the web tool, kindly let us know.

**Comment by romannurik** [comment]
See also #210 ... The new tool I made, https://icon.kitchen has this.

**Comment by r100-stack** [comment]
> See also #210 ... The new tool I made, [icon.kitchen](https://icon.kitchen) has this.

@romannurik It's a nice tool, thanks! Just wondering, is that tool also open source?
