### ISSUE TITLE
[Bug] Icon appearing as a gray square instead of image.

### ISSUE THREAD

**Issue by aschmois** [romannurik/AndroidAssetStudio#25]
If I use a qr code as an image I get a gray square.

Image used:
![qrcode](https://cloud.githubusercontent.com/assets/4064285/5502045/f9dd3f72-8731-11e4-9440-880afce3186f.png)

Result:
![2014-12-19 03_48_19-android asset studio - icon generator - action bar and tab icons](https://cloud.githubusercontent.com/assets/4064285/5502046/feb9f878-8731-11e4-89b2-fc98debe5a88.png)

**Comment by dkokic** [comment]
Probably the same is required for notification icons ... any chance to add this info in the web UI?!
