### ISSUE TITLE
Instructions on how to use this tool (specs for image foregrounds)

### ISSUE THREAD

**Issue by hellocaio** [romannurik/AndroidAssetStudio#250]
It'd be nice to have some sort of instructions on how to you this tool. It looks very useful except I get a white blob when I insert my image. What is the ideal image size? Does it have to be RGB or a different image mode?

**Comment by rodolfosaraiva** [comment]
same issue

**Comment by romannurik** [comment]
If you use the new tool I made [icon.kitchen](https://icon.kitchen), there's now an explicit "Mask" option that more clearly lets you decide if you just want to use the silhouette (alpha channel) of the image you supplied, or if you actually want to use the colors in the image.

With the Asset Studio, if you set the foreground color to transparent, the original image's colors will show up.

**Comment by ahaverty** [comment]
I forget that colours are stripped out by android (and that transparency is important/required), every time I go to do this.
Might be good to add some kind of help text to the tool, this SO answer was my penny-drop moment:
https://stackoverflow.com/a/45318726/2276198
