### ISSUE TITLE
Use consistent file names for adaptive icons, or allow customization

### ISSUE THREAD

**Issue by nokite** [romannurik/AndroidAssetStudio#251]
The file names of the generated adaptive images have changed recently. This breaks our workflow, as we rely on having consistent file names every time we use this tool. We already have a lot of apps using the old names.

It would be great to go back to the previous naming scheme. Or to allow the user to customize the file names, in this case the postfix.

The postfix used to be like "*background":
ic_launcher_background.png
ic_launcher_foreground.png

Now it's like "*adaptive_back":
ic_launcher_adaptive_back.png
ic_launcher_adaptive_fore.png

Right now we're forced to rename the files manually after using this tool, which is quite some work that should be avoided. So if this doesn't get resolved we'd have to fork the project, or write a script to rename the files, which feels like a bad workaround. I imagine that other people must have run into the same problem, so I prefer solving this at the source and sharing my solution.

I can try to open a PR with the change, depending on what the maintainer prefers.
Let me know!

https://github.com/romannurik/AndroidAssetStudio/commit/951c463ef846fdf89d0b413938b1c1b010aa0834#diff-7f35945bac61b3f2b58ce5d461adf27cf2073083697ebe0765ccf9cc892bbc8cR130

**Comment by romannurik** [comment]
Hi there, my new tool [icon.kitchen](https://icon.kitchen) does this. I'm looking to avoid further changes to the Android Asset Studio's launcher icon  generator.
