### ISSUE TITLE
Is it possible to generate the icons from python script based on dynamic data from file?

### ISSUE THREAD

**Issue by hossambusiness** [romannurik/AndroidAssetStudio#252]
im building ci/cd tool and i was hoping if I can use this tool to generate app icons dynamic from python scrip

**Comment by romannurik** [comment]
Hi there! The only feasible way to do this from a script would be to use node, with node-canvas or a headless browser like puppeteer, but even that would require a good amount of work :) I'm closing this as infeasible for this project.
