### ISSUE TITLE
Minor issue (related to icon kitchen)

### ISSUE THREAD

**Issue by nirajniroula** [romannurik/AndroidAssetStudio#260]
When Web Icons preview option is selected from the top bar, the preview section displays both web as well as iOS icon previews.

**Priority: Not that serious/Is that intentional?**  

![image](https://github.com/romannurik/AndroidAssetStudio/assets/11739133/1cb012f1-4045-492f-88c4-509cad2c1f1c)

**Comment by romannurik** [comment]
This is actually working as intended — it's showing the PWA app icon on an iOS device
