### ISSUE TITLE
Add bold/italics/underline formatting for text

### ISSUE THREAD

**Issue by amiv1** [romannurik/AndroidAssetStudio#28]
Right now you can generate icons from the normal text only, though it would be great to be able to add bold, italics and underline formatting to it.

**Comment by nioncode** [comment]
Actually I think it always generates with `bold` text at the moment, which looks weird for some fonts.. It would be great if this could be made customizable.

**Comment by romannurik** [comment]
Heads up! This feature is now available in [IconKitchen](https://icon.kitchen), a new tool I published today for generating Android, iOS, and web app icons. (no current plans to port this to the Android Asset Studio)
