### ISSUE TITLE
Padding for launcher icons goes against iconography guidelines

### ISSUE THREAD

**Issue by InsanityOnABun** [romannurik/AndroidAssetStudio#31]
http://developer.android.com/design/style/iconography.html

According to the guidelines, launcher icons should use all 48dp both ways for the icon, without padding (full asset). The launcher icon generator seems to add a good deal of padding. Not only does this go against the design specs, but it also makes the launcher icons look oddly small next to any other launcher icons.

**Comment by romannurik** [comment]
Those guidelines are deprecated in favor of http://www.google.com/design/spec/style/icons.html#icons-product-icons

**Comment by InsanityOnABun** [comment]
So the padding is in spec then? Hmm. Well hopefully other app devs will fall in line soon, the smaller icons look a bit off surrounded by the old spec, size-wise.
