### ISSUE TITLE
Multi Line Text Input

### ISSUE THREAD

**Issue by MSIH** [romannurik/AndroidAssetStudio#33]
Add the option for second or third line of text to be in the logo generator.

**Comment by passsy** [comment]
`\n` does not work :(

**Comment by romannurik** [comment]
Closing as WAI (launcher icons shouldn't have so much text in them that it crosses multiple lines)

**Comment by Soitora** [comment]
Can this be reopened and reevalued? Google has since officially supported it: https://issuetracker.google.com/issues/131976524

**Comment by Soitora** [comment]
@romannurik Can this be reopened and reevalued? Google has since officially supported it: https://issuetracker.google.com/issues/131976524
