### ISSUE TITLE
Creates mipmap prefixed icons which don't work by default in Android Studio

### ISSUE THREAD

**Issue by kaihendry** [romannurik/AndroidAssetStudio#38]
http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html creates res/mipmap-* prefixed icons. When I unzip that in my app/src/main directory, it doesn't seem to take any effect on a standard Android Studio app.

**Comment by romannurik** [comment]
You'll need to change your references in the manifest to `@mipmap/ic_launcher`
