### ISSUE TITLE
Shuts down monitor

### ISSUE THREAD

**Issue by sogen** [romannurik/AndroidAssetStudio#40]
When trying to use it, it shuts down the monitor!

Just drag & dropping and image makes the monitor go off, can't get it back on, I have to restart the computer .-.

using: 
Chrome 40 (also happened on 39)
Win 7 pro SP1 64 bits
HP Wlitedesk 800 G1 TWR
Intel core i7-4770
8gb RAM
NVIDIA GeForge GT 610

**Comment by romannurik** [comment]
This can't possibly be something caused by the web site… at most it's something with your GPU drivers or similar?

**Comment by sogen** [comment]
It's way way odd, never had this issue, I've only stumbled on this while
trying to add an image.
