### ISSUE TITLE
Please support XXXHDPI...  

### ISSUE THREAD

**Issue by NoamElbaz** [romannurik/AndroidAssetStudio#42]
Thanks.

Waiting for updates.

Noam Elbaz
UI Designer @ Glide

**Comment by dgngulcan** [comment]
+1

**Comment by joerogers** [comment]
Just fixed it for myself. Try this and let me know if it works for you: http://joerogers.github.io/AndroidAssetStudio/

**Comment by Ph1b** [comment]
Please accept the pull request. Google (and android studio) recommend both to use xxxhdpi.

**Comment by githubdoramon** [comment]
@joerogers Awesome... I´ll start using your!

**Comment by benhk2005** [comment]
+1

**Comment by caBBAlainB** [comment]
+1

**Comment by romannurik** [comment]
Just pushed
