### ISSUE TITLE
Why using rectangular shapes for pre-v11 icons?

### ISSUE THREAD

**Issue by daniele-athome** [romannurik/AndroidAssetStudio#45]
https://github.com/romannurik/AndroidAssetStudio/blob/master/src/html/icons-notification.html#L101

Why do you use rectangular shapes for pre-v11 icons? I couldn't find any guideline stating this.

**Comment by jkasten2** [comment]
It looks like Google removed the Android 2.3 status bar icons from their documentation a while a go but you can find these sizes documented from this page snapshot. http://web.archive.org/web/20121025153046/http://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html#icon9

**Comment by daniele-athome** [comment]
Just what I was looking for, thanks!!!
