### ISSUE TITLE
Android TV Asset Generation Support

### ISSUE THREAD

**Issue by tmack8001** [romannurik/AndroidAssetStudio#47]
It would be really cool if there was a generator added for Android TV assets like the Android TV Leanback Launcher Banner.

**Comment by romannurik** [comment]
Ah, launcher banner would be cool for sure.

**Comment by alexeyvasilyev** [comment]
Please add Android TV banner generator as well.

**Comment by ckurtm** [comment]
any chance this will be added?

**Comment by romannurik** [comment]
I'd like to do this but haven't followed enough about what the guidelines/asset needs are for Android TV recently. Definitely makes sense to do this though.

**Comment by adamlucia** [comment]
This feature would be nice. I've been going through a bunch of issues with getting a lean back launcher graphic to fit right on the home screen UI (android:banner in AndroidManifest.xml). I'm having issues with both 160ppi and 320ppi PNG resources. The [documentation ](https://developer.android.com/training/tv/start/start#banner) is sparse, but it says:
> The banner should be an xhdpi resource with a size of 320 x 180 px. Text must be included in the image. If your app is available in more than one language, you must provide separate versions of the banner with text for each supported language.

**Comment by romannurik** [comment]
Heads up! This feature (in a fairly simplified form) is now available in [IconKitchen](https://icon.kitchen), a new tool I published for generating icons across a variety of platforms. (No current plans to port this to the Android Asset Studio)

**Comment by shimiuh** [comment]
I find no way to make ic_ launcher in the correct sizes for TV Any idea's how this is done?
