### ISSUE TITLE
how remove the black border around my Gen images  ??

### ISSUE THREAD

**Issue by moa7amed** [romannurik/AndroidAssetStudio#48]
how remove the black border around my Gen images  ??

**Comment by romannurik** [comment]
Not enough information...

**Comment by moa7amed** [comment]
![the_old_man 9](https://cloud.githubusercontent.com/assets/325766/7216247/39c1f668-e601-11e4-9184-8fecff6d7556.png)

Check my attached pic ... it have borders but in fact no borders i see small borders in 4 sides and spaces between borders  ... can i remove it ??

**Comment by thiagoross** [comment]
Not enough? Man, I'm sorry, but it is clearly visible. Just select any image from your computer on the tool and download the .zip file. Open up any image saved and you will see a black border on the image.

Is there a way to take it off?

By the way, great work with the tool. It would be excellent if the 9 patch tool could be working perfectly :)

**Comment by ibrahimyilmaz7** [comment]
Same dirty borders on my images too, at 2018.

**Comment by romannurik** [comment]
Those borders are part of the nine patch. Android reads that information to decide how to stretch your image.
