### ISSUE TITLE
Include new material icons in asset studio

### ISSUE THREAD

**Issue by ZakTaccardi** [romannurik/AndroidAssetStudio#52]
[This commit](https://github.com/google/material-design-icons/commit/bf943d97aa6e4628f05eef91e6b5563af4e7de3d) added a bunch of new icons, but they are not in Android Asset Studio yet.

I am uploading all the svg production icons into [this Google Drive folder](https://drive.google.com/folderview?id=0B_pmIb5e_cfifmV5dF83VG1WOWdxQlBpUzdEdmVWdlptcC1FalVIbDlFZF9wSHFZS0c2NnM&usp=sharing), if that proves useful. I renamed them according to the naming conventions the asset studio currently uses.

**Comment by romannurik** [comment]
Updated
