### ISSUE TITLE
Long Shadow and Score?

### ISSUE THREAD

**Issue by klauswuestefeld** [romannurik/AndroidAssetStudio#53]
The long shadow and score effects appear to do nothing.

http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.space.trim=1&foreground.space.pad=0&foreground.clipart=res%2Fclipart%2Ficons%2Faction_account_balance.svg&foreColor=607d8b%2C0&crop=0&backgroundShape=square&backColor=ffffff%2C100&effects=shadow

**Comment by AaronLayton** [comment]
Seems to be working for me - you can easily see the shadow in the top left. Try increasing the padding around the icon

**Comment by Pedramrn** [comment]
Hi...
I think long shadow is a little too pale. it would be nice to have an option to adjust it.

thanks

**Comment by garywzh** [comment]
Yes, I also think long shadow is too pate, On my phone, almost nobody can find it got shadow there.
