### ISSUE TITLE
Shrink on Square shape

### ISSUE THREAD

**Issue by SHi-ON** [romannurik/AndroidAssetStudio#54]
Hi,

in Launcher Icon Generator, when Shape = Square selected, the result image shrank and displayed a little bit smaller than other icons in android launcher.

If you make it normal like Shape = Bevel, that becomes the best choice in this field.

**Comment by winsontan520** [comment]
This bug still exist as selecting the Square, the padding will increase comparing to other

**Comment by romannurik** [comment]
Compare the generated square to the Google Maps or Google Keep icon. The square is the correct size per the spec.
