### ISSUE TITLE
"Failed - No file"

### ISSUE THREAD

**Issue by lolobosse** [romannurik/AndroidAssetStudio#64]
I spotted a bug, happening on Chrome (didn't tested it on other browsers)
- Upload a picture (I used png)
- Rename the output
- Chrome says `Download failed, no File`

If someone is interested, I made a command to rename it in terminal (because I couldn't rename in the Web Version):

``` bash
find . -name '*.png' -exec sh -c 'mv "$0" ""$(dirname "$0")"/{NewName}.png"' {} \;
```

I used the [online version](http://romannurik.github.io/AndroidAssetStudio/icons-generic.html).

**Comment by romannurik** [comment]
reproduced the problem, thanks for filing!
