### ISSUE TITLE
hardcoded padding?

### ISSUE THREAD

**Issue by mlostekk** [romannurik/AndroidAssetStudio#65]
Hello there,

first of all GREAT TOOL! Thanks for this!

I have one question (maybe not an issue, maybe my fault). 

If i am trying to generate a bunch of launcher icons for me, it seems there is always a padding set even though i set it to 0%. Is this intended? Or should i set the padding to a negative value to fill all the available space with my icon (without cutting it)

**Comment by damson** [comment]
:+1:

**Comment by romannurik** [comment]
Can you share a screenshot?

**Comment by eligrey** [comment]
@romannurik Does Android Asset Studio have any hard coded padding?
