### ISSUE TITLE
Why the generated Launcher Icon has a transparent border

### ISSUE THREAD

**Issue by SeanWxy** [romannurik/AndroidAssetStudio#68]
I aappreaciate for the convience of dealing with my assets, but how can I remove the transparent border from the launcher icon?
![2](https://cloud.githubusercontent.com/assets/10905373/10334684/5f3b965c-6d1e-11e5-9a2c-60f5a5d13e15.png)

**Comment by romannurik** [comment]
Material design product icons include padding on purpose, to allow for optical size consistency between shapes and shadows.

**Comment by SeanWxy** [comment]
I don't know this before and I googled. Thank you.
