### ISSUE TITLE
Shapes shows just a black bagground.

### ISSUE THREAD

**Issue by Muuddz** [romannurik/AndroidAssetStudio#71]
When i import a image file and choose SQURE as shape, the shapes only show as black

**Comment by tmaxxdd** [comment]
I have this problem too :(

**Comment by romannurik** [comment]
Can you attach a screenshot? Also make sure you've tried all the color and opacity (slider) settings.

**Comment by AbuMuddz** [comment]
All possible combination of the different colors,shape and settings has been tried without any succses.
Only the shapes BEVEL and NONE, shows the uploaded logo. The rest of the shapes just shows as plain black

Brower: Google Chrome Version 46.0.2490.71 m.
OS: Windows  7

![udklip](https://cloud.githubusercontent.com/assets/14817640/10560435/c3bafee8-750b-11e5-9e06-7c7458453cff.JPG)

**Comment by santigallego9** [comment]
@AbuMuddz @romannurik At first I was having the same problem on Google Chrome, but it seems to me that it is a issue with the functionality with the browser because I have always used Google Chrome and it has always worked for me until now, yet it still works on Microsoft Edge, a little slower, but it works.
![screenshot 2015-10-17 22 58 56](https://cloud.githubusercontent.com/assets/14914091/10562459/bf0cf86c-7522-11e5-9cfb-ebac755d34ad.png)

**Comment by santigallego9** [comment]
I cannot seem to be able to download a zip file however using Edge

**Comment by AbuMuddz** [comment]
I just downloaded Mozilla Firfox and it worked perfectly!

**Comment by AbuMuddz** [comment]
Why is generator creating so much empty room? It makes the laucher icon smaller than it should be on the phone

![udklip](https://github-cloud.s3.amazonaws.com/assets/14817640/10565748/9419fac2-75d8-11e5-969e-9bc75122e179.JPG)

**Comment by santigallego9** [comment]
You may have already done it but if you tell android studio to remove surrounding blank space when creating the image asset, it makes it a little bigger.

**Comment by AbuMuddz** [comment]
@santigallego9  Dayum thanks! I didn't know that there was an Asset Studio(generator) in Android Studio :D

**Comment by santigallego9** [comment]
@AbuMuddz anytime!

**Comment by romannurik** [comment]
The empty space around the icon is intentional. Please see the [material design product icons spec](https://www.google.com/design/spec/style/icons.html).

**Comment by AbuMuddz** [comment]
But should it make it that small? look at the colorpickertest icon and the other icons compared

![screenshot_2015-10-18-20-34-56](https://github-cloud.s3.amazonaws.com/assets/14817640/10566224/16af9606-75e1-11e5-8487-8655112294db.png)

**Comment by mattbright** [comment]
I had the same black icon (only in shapes) issue, but the issue disappeared as soon as chrome updated itself to (stable channel) 47.0.2526.73m

**Comment by jon80** [comment]
I am happy to hear this, I will update my previous boss, maybe it is relevant to his developer or the software development department, hoping he is not too disturbed with my helpful email.
This had been a problem as my icons had shades of yellow and black, so I could afford having a completely black background, in terms of design.

Regards,

J. CamilleriMalta, EU

Date: Mon, 7 Dec 2015 16:07:44 -0800
