### ISSUE TITLE
Launcher icons are generated too small because of margin

### ISSUE THREAD

**Issue by johnjohndoe** [romannurik/AndroidAssetStudio#73]
I am trying to [**generate launcher icons**](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html) as shown in the screenshot:

![Android Asset Studio - icon generator - launcher icons](https://cloud.githubusercontent.com/assets/144518/10635352/5c061658-77f8-11e5-9b41-af331637258b.png)

For some reason there is **margin around each launcher icon** as indicated here:

![Indicating padding](https://cloud.githubusercontent.com/assets/144518/10635386/a7df8528-77f8-11e5-86ce-e70be0f818b5.png)

This causes the icons to be **much smaller then any other icon** on a device as shown here:

![Comparing icons sizes on the device](https://cloud.githubusercontent.com/assets/144518/10635577/0e8380f8-77fa-11e5-8a10-f64a2c6a03b9.png)

Is this a bug?

---

### Similar discussions

* Shapes shows just a black bagground, #71 
* hardcoded padding?, #65 
* Padding is inserted when using Bevel, #58

**Comment by romannurik** [comment]
This is not a bug. Please refer to the [material design product icon grid](https://www.google.com/design/spec/style/icons.html#icons-product-icons), which specifies the padding for square and circle shapes. In the screenshot you shared, notice how the Test icon square is the same size as the square in the Maps icon.

**Comment by mlostekk** [comment]
It seems to me that the link you shared is not considered by any other developer. If i am using the icon generated by your (indeed awesome) asset studio, the icon looks smaller then other (also just rounded square) icons in my launcher.

**Comment by marcomilone** [comment]
Hi...
Your tool is very powerful and well working.
Btw I agree with Simon and I'll ask you for 2 more customization options:

1 - a flag to generate a shadow AFTER the icon is generated (at the and of your script) (not counted for alignement purposes)
The Asus filemanager have a wonderful shadow balance
https://play.google.com/store/apps/details?id=com.asus.filemanager

2 - a flag to indicate: dont' give any padding.
As stated by Jennifer, neither google respect icon size.
That way If I give you an icon with shadow, my shadow is counted in alignement counts and is misaligned in the grid.
I have to put the shadow AFTER your script generate the n icons in each png.
OR
I have to open each PNG and realign them.

**Comment by robinsingh-bw** [comment]
Where do we edit the code to get rid of this padding (without going through every file)?

**Comment by marcostomasello** [comment]
First of all, this tool is awesome and so the Material Design guidelines. Having said that, for those who want their icons a little bigger, here it's a simple way: 
@robinsingh-bw in app/scripts/pages/LauncherIconGenerator.js look for this

`const TARGET_RECTS_BY_SHAPE = {
  none: { x:  3, y:  3, w:  42, h:  42 },
  circle: { x:  2, y:  2, w:  44, h:  44 },
  square: { x:  5, y:  5, w:  38, h:  38 },
  vrect: { x:  8, y:  2, w:  32, h:  44 },
  hrect: { x:  2, y:  8, w:  44, h:  32 },
};`

Then you can change square (for example) to something like that:
`square: { x:  2, y:  2, w:  44, h:  44 },`

**Comment by akgoal** [comment]
You can do what @marcostomasello suggested directly from Google Chrome (maybe other browsers, too, but I haven't tried). Here's what you need to do:

Right click - Inspect (Ctrl+Shift+I). Select "Sources" tab. There, navigate to  top/romannurik.github.io/AndroidAssetStudio/scripts/app.js. You should see a javascript file opened. 

Now, you need to modify the file before its execution. To do that, add a breakpoint on the first line (just click on the line number "1"). Reload the page. Now that the script execution is paused, locate this line (you can Ctrl+F it):
`TARGET_RECTS_BY_SHAPE={none:{x:3,y:3,w:42,h:42},circle:{x:2,y:2,w:44,h:44},square:{x:5,y:5,w:38,h:38},vrect:{x:8,y:2,w:32,h:44},hrect:{x:2,y:8,w:44,h:32}}`

Modify the line however suits you best. Then save the file (Ctrl+S) and resume execution (Ctrl+\\) (you can also remove the breakpoint if you don't plan on modifying anything later). Voila!

Note that you have to do this everytime you load the page. So I would advise to construct and perfect the icon first (with padding) and then remove padding by this method.

**Comment by androidovshchik** [comment]
I have build such a fixed version
Check out it here
https://androidovshchik.github.io/AndroidAssetStudio

**Comment by johnjohndoe** [comment]
@androidovshchik :+1: You might want to open a pull request for @romannurik.

**Comment by androidovshchik** [comment]
> @androidovshchik  You might want to open a pull request for @romannurik.

I think it is wrong to limit the possibilities for the user, even despite the guides. I myself corrected the script many times on the original site, but i got tired. I don’t know, maybe I should do it, but probably in a different form. Here is a quick fix

**Comment by ChrisEelmaa** [comment]
thanks @androidovshchik, the way it should be done. Doesn't really make sense to generate an icon that looks visually incorrect (eg you have 20 other OFFICIAL app icons that look much bigger than the one that was generated because of "guidelines")

**Comment by whenmoon** [comment]
Wow glad I found this - was very frustrating to not be able to generate at the right size. But yes, this is an awesome tool!
