### ISSUE TITLE
Colors not applied in new google chrome update

### ISSUE THREAD

**Issue by amehdi** [romannurik/AndroidAssetStudio#74]
I don't know from which version this behavior begins; but currently in chrome version 46.0.2490.71 m (for windows) the custom color doesn't work neither in "Generic icons" nor in "Action Bar and Tab Icon".

**Comment by benleunginnopage** [comment]
same issue with chrome 46.0.2490.71

**Comment by bill-mybiz** [comment]
Same with 46.0.2490.80

**Comment by romannurik** [comment]
Is this a duplicate of #71?

**Comment by amehdi** [comment]
@romannurik Absolutely not! It is about color overlays.

**Comment by bill-mybiz** [comment]
IMHI, the issue manifestation may not be a duplicate per se, but that they
both fail in chrome but succeed in other browsers and that it affects
colorization suggests that there is a good chance the root cause is related.

**Comment by romannurik** [comment]
Which OS are you running Chrome on? Works fine on Chrome 46.0.2490.80 running on a Mac…

**Comment by benleunginnopage** [comment]
Windows 7

**Comment by bill-mybiz** [comment]
I'm on Windows 10.

**Comment by amehdi** [comment]
mine is Windows 8.1
It seems we should mention someone from Google Chrome team here since its obviously a browser issue.

**Comment by tmdues** [comment]
I'm seeing the same issue on chrome (46.0.2490.80) for Windows 7

**Comment by 3lywa** [comment]
Same issue here on Windows 10 with Chrome 46.0.2490.80 m

**Comment by benleunginnopage** [comment]
If mac is ok, then is it a chrome bug?

**Comment by vipulyaara** [comment]
Same issue on Chrome Version 46.0.2490.71 m, Windows 8.1.

**Comment by garywzh** [comment]
Same issue on Win7 with chrome 46.0.2490.80 m

**Comment by smrehan6** [comment]
same here chrome Version 46.0.2490.80 m win7

**Comment by TomasValenta** [comment]
Same on W10 and Chrome 46.0.2490.80 m

**Comment by RudolfHladik** [comment]
same issue Version 46.0.2490.80 m, OS Win 10

**Comment by derAndroidPro** [comment]
Same issue in Chrome on Windows 10: http://prntscr.com/8zr139

**Comment by easyaspi314** [comment]
Same in 46.0.2490.80 m on Vista x86.

**Comment by easyaspi314** [comment]
This is important: **It works on Opera 33.0**, same Chromium engine version (to the decimal point, 46.0.2490.86), same computer, side-by-side: 

![It works in opera](https://cloud.githubusercontent.com/assets/6258309/11290626/77aa22e4-8f06-11e5-91ab-5a37382aba7c.png)

Works: Opera 33.0.1990.115 - `Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 OPR/33.0.1990.115`
Doesn't work: Chrome 46.0.2490.80 m - `Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36`

**Comment by amehdi** [comment]
It seems the problem solved in new release of chrome on windows (Version 47.0.2526.73 m).

**Comment by jon80** [comment]
How was it resolved, please?

Date: Wed, 2 Dec 2015 23:11:34 -0800
