### ISSUE TITLE
Image gone for large images

### ISSUE THREAD

**Issue by kriskast** [romannurik/AndroidAssetStudio#77]
Hi, I noticed that when I put an icon and scale it up large some of the results end up being just the selected color.
![042eaeb609db824f7dcbd0d79b3cfc30 1](https://cloud.githubusercontent.com/assets/12373559/10923437/24da7528-8281-11e5-9137-d18e4fdc8e4b.png)

**Comment by romannurik** [comment]
Please test again with the new version of the tool, and re-open if anything.
