### ISSUE TITLE
Different collors on higher sizes when using shape bevel

### ISSUE THREAD

**Issue by asworm** [romannurik/AndroidAssetStudio#84]
I passed over here just to post this bug.
When I download the icons they came as they are shown in the picture.

![issuegit](https://cloud.githubusercontent.com/assets/12392487/11625418/cf43948e-9cd2-11e5-8b77-174dff770096.png)

Thank you, very usefull tool

**Comment by romannurik** [comment]
Looks like a glfx blur bug... Thanks for the report!

**Comment by romannurik** [comment]
This is likely now resolved.
