### ISSUE TITLE
Feature Request:  Ability to upload own TTF font.

### ISSUE THREAD

**Issue by tuckercr** [romannurik/AndroidAssetStudio#86]
Hi, we use our own custom font that we use for icon generation.  Please add the ability to upload our own TTF file to generate notification & action icons from.  Currently I have to export a png from the font which is somewhat time consuming.  Thanks, Colin

**Comment by romannurik** [comment]
This is out of scope since this tool is client side only

**Comment by tuckercr** [comment]
no worries, the improvements in Vector support make this ticket obsolete now anyway.
