### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by FrankCharlz** [romannurik/AndroidAssetStudio#88]
Users should be able to search by icon name, I think it will make it more easier to use

**Comment by romannurik** [comment]
Do you mean searching clipart? That's already possible:

![screen shot 2016-01-19 at 2 16 36 pm](https://cloud.githubusercontent.com/assets/100155/12429273/4904215c-beb7-11e5-894c-a5791a5492b2.png)

**Comment by FrankCharlz** [comment]
Ok sorry I didn't know that,
