### ISSUE TITLE
Remove CC-BY relicensing requirement

### ISSUE THREAD

**Issue by eligrey** [romannurik/AndroidAssetStudio#95]
This project is Apache licensed, so the CC-BY relicensing clause is toothless since I can simply remove that requirement from a fork of this project.

Please remove the CC-BY relicensing stuff from the official app because I can do it myself, and people will prefer to use my fork that doesn't include such a restriction.

**Comment by romannurik** [comment]
removed

**Comment by eligrey** [comment]
Thanks for fixing this.
